spring:
  datasource:
    mariadb:
      url: jdbc:mariadb://localhost:3306/undergraduate_thesis?useLegacyDatetimeCode=false&serverTimezone=UTC
      username: root
      password: 112
      driver-class-name: org.mariadb.jdbc.Driver
    postgresql:
      url: jdbc:postgresql://localhost:5432/undergraduate_thesis?useLegacyDatetimeCode=false&serverTimezone=UTC
      username: postgres
      password: 112
mqtt:
  broker-url: tcp://broker.emqx.io:1883
  client-id: backend-service
  username: mqtt_user
  password: mqtt_password

jwt:
  secret-key: "Q^*]U3$H64:ymD'jE_SL?;tc@7P`&p:(9uFR>d=!A2)G5}%vnk:"
  time-out: 2000000